name: SpawnCommand
version: 1.2
api: [3.0.0]
author: WortTuner
main: SpawnCommand\Main

commands:
  spawn:
    description: "Teleport to spawn"
    usage: "/spawn"
    permission: "spawncommand.command.spawn"

permissions:
  spawn:
    default: true
    description: "Teleport Your Self to Server Spawn"

